import { Button } from "@/components/ui/button"
import { Music2, Sparkles, Share2, Zap } from 'lucide-react'
import Link from 'next/link'
import { db } from "@/lib/db"

export default async function LandingPage() {
  const profileCount = await db.profile.count()

  return (
    <div className="relative flex min-h-screen flex-col items-center justify-center overflow-hidden bg-background px-6 text-foreground">
      {/* Background Glow */}
      <div className="absolute inset-0 -z-10 overflow-hidden">
        <div className="absolute -top-[10%] -left-[10%] h-[40%] w-[40%] rounded-full bg-primary/20 blur-[120px]" />
        <div className="absolute bottom-0 right-0 h-[30%] w-[30%] rounded-full bg-primary/10 blur-[120px]" />
      </div>

      <main className="z-10 flex flex-col items-center text-center">
        <div className="mb-8 flex animate-bounce items-center gap-2 rounded-full border border-primary/20 bg-primary/5 px-4 py-1.5 text-sm font-medium text-primary">
          <Sparkles className="h-4 w-4" />
          <span>{profileCount > 0 ? `Join ${profileCount.toLocaleString()}+ music lovers` : "Be the first to join"}</span>
        </div>
        
        <h1 className="max-w-4xl text-5xl font-extrabold tracking-tight sm:text-8xl mb-6">
          Your Sound, <br />
          <span className="bg-gradient-to-r from-primary to-primary/60 bg-clip-text text-transparent">
            Visualized.
          </span>
        </h1>

        <p className="max-w-2xl text-lg text-muted-foreground sm:text-xl mb-12">
          Go beyond the genres. Discover the DNA of your music personality through deterministic metrics and AI-powered archetypes.
        </p>

        <div className="flex flex-col sm:flex-row gap-4">
          <Link href="/dashboard">
            <Button size="lg" className="h-14 px-10 text-lg font-bold gap-2 shadow-lg shadow-primary/20">
              Get Started <Music2 className="h-5 w-5" />
            </Button>
          </Link>
          <Link href="/explore">
            <Button variant="outline" size="lg" className="h-14 px-10 text-lg font-bold gap-2">
              Explore Gallery <Zap className="h-5 w-5" />
            </Button>
          </Link>
        </div>

        {/* Feature Grid */}
        <div className="mt-24 grid grid-cols-1 gap-8 sm:grid-cols-3 max-w-5xl">
          <div className="flex flex-col items-center p-6 rounded-3xl border border-white/5 bg-white/5 backdrop-blur-sm">
            <div className="mb-4 rounded-2xl bg-primary/10 p-3">
              <Zap className="h-6 w-6 text-primary" />
            </div>
            <h3 className="font-bold mb-2">Instant Analysis</h3>
            <p className="text-sm text-muted-foreground">Deep dive into your top 50 tracks and artists in seconds.</p>
          </div>
          <div className="flex flex-col items-center p-6 rounded-3xl border border-white/5 bg-white/5 backdrop-blur-sm">
            <div className="mb-4 rounded-2xl bg-primary/10 p-3">
              <Sparkles className="h-6 w-6 text-primary" />
            </div>
            <h3 className="font-bold mb-2">AI Archetypes</h3>
            <p className="text-sm text-muted-foreground">Generated by Gemini 1.5 Flash for unique, cinematic personalities.</p>
          </div>
          <div className="flex flex-col items-center p-6 rounded-3xl border border-white/5 bg-white/5 backdrop-blur-sm">
            <div className="mb-4 rounded-2xl bg-primary/10 p-3">
              <Share2 className="h-6 w-6 text-primary" />
            </div>
            <h3 className="font-bold mb-2">Vibe Check</h3>
            <p className="text-sm text-muted-foreground">Compare your music DNA with friends and see your match score.</p>
          </div>
        </div>
      </main>

      <footer className="mt-24 pb-12 text-sm text-muted-foreground">
        Built with Next.js 15 & Gemini
      </footer>
    </div>
  )
}
